Fixes #6 AuthorityTests
AssertionError: did not expect err:Unicode-objects must be encoded
before hashing
is thrown from CacheDriver for the following Tests:
test_success_dynamic_instance_discovery
test_success_static_instance_discovery
test_validation_off

They should be fixed post #7 CacheDriver fixes